import { useState, ChangeEvent, useEffect } from "react";
import useAxios from "axios-hooks";

import Head from "next/head";
import {
  Container,
  Box,
  Stack,
  Flex,
  Button,
  Text,
  VStack,
  useBreakpointValue,
  Heading,
  Image,
  FormControl,
  Input,
  HStack,
} from "@chakra-ui/react";
import { IBM_Plex_Mono, Dancing_Script } from "@next/font/google";
import { ReactElement } from "react";
import FullWidthLayout from "../components/Layout/FullWidthLayout";
import Features from "../components/Features";

const inter = IBM_Plex_Mono({ subsets: ["latin"], weight: "700" });
const dancing = Dancing_Script({ subsets: ["latin"], weight: "700" });
export default function Home() {
  const [email, setEmail] = useState<string>("");

  const [{ data, loading, error }, refetch] = useAxios(
    {
      url: "/api/emailSignup",
      method: "POST",
      data: { email },
    },
    {
      manual: true,
    }
  );
  useEffect(() => setEmail(""), []);

  useEffect(() => {
    if (data?.success === true && !loading) {
      setEmail("");
    }
  }, [data?.success, loading]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        w={"full"}
        h={"100vh"}
        backgroundImage={"url(eat2beat-hero.jpg)"}
        backgroundSize={"cover"}
        backgroundPosition={"center center"}
      >
        <VStack
          w={"full"}
          justify={"center"}
          px={useBreakpointValue({ base: 4, md: 8 })}
        >
          <Stack
            width={"950px"}
            align={"flex-start"}
            spacing={12}
            backgroundColor="white"
            backgroundImage={"url(plate.jpg)"}
            backgroundSize={"cover"}
            backgroundPosition={"center center"}
            py={24}
            px={12}
            borderRadius={12}
            boxShadow={"2xl"}
            marginTop={12}
          >
            <Text
              color={"black.900"}
              fontWeight={700}
              lineHeight={1.6}
              fontSize={useBreakpointValue({ base: "3xl", md: "4xl" })}
              className={inter.className}
            >
              Unlock Your
              <br />
              <Text color={"ms.900"}>Health Potential</Text>
              With&nbsp;Personalized Diet
            </Text>
            <Stack direction={"row"}>
              <Button>Show me more</Button>
              <Button
                bg={"whiteAlpha.300"}
                rounded={"full"}
                color={"black"}
                _hover={{ bg: "whiteAlpha.500" }}
                onClick={() => {
                  const info = document.querySelector("#info");
                  if (!info) return;
                  info.scrollIntoView({ behavior: "smooth" });
                }}
              >
                Read more
              </Button>
            </Stack>
            <Box paddingTop={12}>
              <Image src="Eat2beat-logos-WIP.svg" alt="Logo" height={16} />
            </Box>
          </Stack>
        </VStack>
      </Flex>

      <Container maxW={"6xl"} id="info">
        <Features />
        <Stack
          as={VStack}
          spacing={8}
          alignItems={"center"}
          justifyContent={"center"}
          textAlign={"center"}
          py={12}
        >
          <Heading>
            Get your 7-day meal plan by subscribing to our newsletter!
          </Heading>
          <Text>
            As a subscriber, you&apos;ll receive an example 7-day meal plan as
            well as updates on our latest project updates and blog posts.
            <br />
            Don&apos;t miss out on the opportunity to improve your health and
            reach your wellness goals.
          </Text>
          <HStack>
            {data?.success === true && !loading ? (
              <Text color={"ms.900"}>Thank you for subscribing.</Text>
            ) : (
              <>
                <FormControl>
                  <Input
                    variant={"solid"}
                    borderWidth={1}
                    color={"gray.800"}
                    _placeholder={{
                      color: "gray.400",
                    }}
                    id={"email"}
                    type={"email"}
                    required
                    placeholder={"Your Email"}
                    aria-label={"Your Email"}
                    value={email}
                    onChange={(e: ChangeEvent<HTMLInputElement>) =>
                      setEmail(e.target.value)
                    }
                  />
                </FormControl>
                <Button mx={4} onClick={() => refetch()} disabled={loading}>
                  Sign up
                </Button>
              </>
            )}
          </HStack>
        </Stack>
      </Container>
    </>
  );
}

Home.getLayout = function (page: ReactElement) {
  return <FullWidthLayout>{page}</FullWidthLayout>;
};
